name: Announce vote on Discord

on:
  workflow_call:
    inputs:
      choices:
        required: true
        type: string
      voting_instructions:
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true

env:
  USERNAME: "PL Reading Group Paper Vote"
  AVATAR: https://raw.githubusercontent.com/the-au-forml-lab/plgroup/main/.github/assets/vote.png

jobs:
  announce_options:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        options: ${{ fromJSON(inputs.choices) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: set variables
        id: vars
        run: |
          npm run set -- "${{ matrix.options }}"
          SHA=$(echo ${{ matrix.options }} | sha256sum | head -c6)
          echo "color=$((16#$SHA))" >> $GITHUB_OUTPUT
          echo "suffix=$SHA" >> $GITHUB_OUTPUT
          cat data/vars.txt >> $GITHUB_OUTPUT
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v6
        id: pr
        with:
          labels: paper-vote,next-paper
          branch: paper-vote-${{ steps.vars.outputs.suffix }}
          title: ${{ fromJSON(steps.vars.outputs.title) }}
          body: ${{ fromJSON(steps.vars.outputs.body) }}
          delete-branch: true
      - name: Post vote option to Discord
        uses: Ilshidur/action-discord@master
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        env:
          DISCORD_AVATAR: ${{ env.AVATAR }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_EMBEDS: |-
            [{ "color": "${{ steps.vars.outputs.color }}",
               "title": ${{ steps.vars.outputs.title }},
               "url": "${{ fromJSON(steps.vars.outputs.doi) }}",
               "description" : ${{
                             toJSON(format('{0}{3}{3}[Merge PR {1}]({2})',
                                           fromJSON(steps.vars.outputs.citation),
                                           steps.pr.outputs.pull-request-number,
                                           steps.pr.outputs.pull-request-url,
                                           fromJSON('"\n"'))) }}
            }]

  post_actions:
    needs: announce_options
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          VT=$(cat ${{ inputs.voting_instructions }} | jq --raw-input --slurp)
          echo "VOTING=$VT" >> $GITHUB_ENV
      - uses: Ilshidur/action-discord@master
        env:
          DISCORD_AVATAR: ${{ env.AVATAR }}
          DISCORD_USERNAME: ${{ env.USERNAME }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: ${{ fromJSON(env.VOTING) }}
